# .github/workflows/ci-pipeline.yml

name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit  # If you need to pass secrets to the build workflow

  test:
    uses: ./.github/workflows/docker-test.yml
    needs: build  # This ensures that the test job runs after the build job
    secrets: inherit  # If you need to pass secrets to the test workflow
