name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $

          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/emlo4-session-05-ajithvcoder:latest .

      # Push the Docker image to GitHub Container Registry (GHCR)
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/emlo4-session-05-ajithvcoder:latest
