name: ML Training Workflow with DHCR

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull DHCR Image
      run: docker pull ghcr.io/ajithvcoder/emlo4-session-05-ajithvcoder:sha-9199afd

    - name: Run training in DHCR container
      run: |
        docker run --rm \
          -v ${PWD}:/workspace \
          ghcr.io/ajithvcoder/emlo4-session-05-ajithvcoder:sha-9199afd \
          bash -c "python src/train.py"

    - name: Upload model checkpoint
      uses: actions/upload-artifact@v3
      with:
        name: model-checkpoint
        path: model_storage/
        retention-days: 20

    - name: Upload training logs
      uses: actions/upload-artifact@v3
      with:
        name: training-logs
        path: logs/
        retention-days: 20

    - name: Upload config
      uses: actions/upload-artifact@v3
      with:
        name: all-config
        path: configs/
        retention-days: 20