name: ML Training Workflow with DHCR

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull DHCR Image
      run: docker pull ghcr.io/ajithvcoder/emlo4-session-05-ajithvcoder:sha-9199afd

    - name: Run training in DHCR container
      run: |
        docker run --rm \
          -v ${PWD}:/workspace \
          ghcr.io/ajithvcoder/emlo4-session-05-ajithvcoder:sha-9199afd \
          bash -c "python train.py"

    - name: Upload model checkpoint
      uses: actions/upload-artifact@v3
      with:
        name: model-checkpoint
        path: model_storage/
        retention-days: 20

    - name: Upload training logs
      uses: actions/upload-artifact@v3
      with:
        name: training-logs
        path: logs/
        retention-days: 20

    - name: Upload config
      uses: actions/upload-artifact@v3
      with:
        name: all-config
        path: configs/
        retention-days: 20